[[algorithms-linkprediction-adamic-adar]]
= The Adamic Adar algorithm

[abstract]
--
This section describes the Adamic Adar Similarity algorithm in the Neo4j Graph Algorithms library.
--

// tag::introduction[]
link:https://en.wikipedia.org/wiki/Adamic/Adar_index[Adamic Adar similarity] is a measure used to compute similarity between nodes based on their shared neighbors.
// end::introduction[]


[[algorithms-linkprediction-adamic-adar-context]]
== History and explanation

// tag::explanation[]

Adamic Adar similarity was introduced in 2003 by Lada Adamic and Eytan Adar to https://www.semanticscholar.org/paper/Friends-and-neighbors-on-the-Web-Adamic-Adar/39348c10c90be968357e2a6b65d5e0e479307735[predict links in a social network^].
It is computed using the following formula:

image::adamic-adar-similarity.svg[role="middle"]

where `N(u)` is the set of nodes adjacent to `u`.

A value of 0 indicates that two nodes are dissimilar, while higher values indicate nodes are more similar.

The library contains a function to calculate similarity between two nodes.

// end::explanation[]

[[algorithms-linkprediction-adamic-adar-usecase]]
== Use-cases - when to use the Adamic Adar Similarity algorithm

// tag::use-case[]
We can use the Adamic Adar Similarity algorithm to work out the similarity between two nodes.
We might then use the computed similarity as part of a link prediction solution.
// end::use-case[]


[[algorithms-linkprediction-adamic-adar-sample]]
== Adamic Adar algorithm sample

.The following will create a sample graph:
[source, cypher]
----
include::scripts/linkprediction-adamic-adar.cypher[tag=create-sample-graph]
----

.The following will return the similarity of Michael and Karin:
[source, cypher]
----
include::scripts/linkprediction-adamic-adar.cypher[tag=all-rels]
----

// tag::function[]
.Results
[opts="header",cols="1"]
|===
| `similarity`
| 1.4426950408889634
|===
// end::function[]


We can also compute the similarity between a pair of nodes based on a specific relationship type.

.The following will return the similarity of Michael and Karin based only on `FRIENDS` relationships:
[source, cypher]
----
include::scripts/linkprediction-adamic-adar.cypher[tag=only-friends]
----

// tag::function[]
.Results
[opts="header",cols="1"]
|===
| `similarity`
| 0.0
|===
// end::function[]


[[algorithms-linkprediction-adamic-adar-syntax]]
== Syntax

.The following will run the algorithm and return the result:
[source, cypher]
----
RETURN algo.linkprediction.adamicAdar(node1:Node, node2:Node, {
    relationshipQuery: null,
    direction: "BOTH"
})
----


.Parameters
[opts="header",cols="1,1,1,1,4"]
|===
| Name                   | Type    | Default        | Optional | Description
| `node1`                   | Node    | null           | no       | A node
| `node2`                   | Node    | null           | no       | Another node
| `relationshipQuery`                   | String    | null           | yes       | The relationship type used to compute similarity between `node1` and `node2`
| `direction`                   | String    | BOTH           | yes       | The direction of relationship type used to compute similarity between `node1` and `node2`
|===
