[[projected-graph-model]]
= Projected Graph Model

ifdef::env-docs[]
[abstract]
--
This chapter explains the projected graph model used by the Neo4j Graph Algorithms library.
--
endif::env-docs[]

Graph algorithms run on an in memory projected graph model.
The projected graph model is separate from Neo4j's stored graph model to enable fast caching for the topology of the graph, containing only relevant nodes, relationships and weights.
The projected graph model does not support multiple relationships between a single pair of nodes.

We can project the graph we want to run algorithms on with either label and relationship-type projection, or cypher projection.

[ditaa]
----
+----------+label/rel type projection +-----------+
|  Neo4j   +------------------------->| Projected |  Execute algorithm
| stored   |    cypher projection     |   graph   |<-------------------
|  graph   +------------------------->|           |
+----------+                          +-----------+

----


During projection, only one relationship between a pai`r of nodes per direction (in, out) is allowed in the directed case, but two relationships are allowed for BOTH the undirected cases.

The library supports two approaches for loading projected graphs:

* <<label-relationship-type-projection, Label and relationship-type projection>>
* <<cypher-projection, Cypher projection>>

include::projected-graph-model/label-relationship-type-projection.adoc[leveloffset=2]
include::projected-graph-model/cypher-projection.adoc[tag=overview,leveloffset=2]





